package dev.starsector.preflight.synthetic;

import dev.starsector.preflight.core.Hashes;
import dev.starsector.preflight.core.Json;
import dev.starsector.preflight.core.PreparedAudio;
import dev.starsector.preflight.core.PreparedAudioCache;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Additive synthetic workload for medium/large corpora, JARs, audio, and generated bytecode. */
public final class SyntheticExtendedStartupWorker {
    private static final String AUDIO_DECODER_POLICY_IDENTITY_SHA256 = Hashes.sha256(
            "synthetic-java-audio-pcm-signed-16le-v1".getBytes(StandardCharsets.UTF_8));

    private SyntheticExtendedStartupWorker() {
    }

    public static void main(String[] args) {
        if (args.length != 3) {
            System.err.println(
                    "Usage: SyntheticExtendedStartupWorker <profile-root> <cache-root> <report.json>");
            System.exit(2);
        }
        try {
            run(Path.of(args[0]), Path.of(args[1]), Path.of(args[2]));
        } catch (ThreadDeath | VirtualMachineError fatal) {
            throw fatal;
        } catch (Throwable error) {
            error.printStackTrace(System.err);
            System.exit(1);
        }
    }

    static void run(Path profileRoot, Path cacheRoot, Path reportPath) throws IOException {
        Path profile = profileRoot.toAbsolutePath().normalize();
        Path cache = cacheRoot.toAbsolutePath().normalize();
        SyntheticExtendedProfile.Manifest manifest = SyntheticExtendedProfile.readManifest(profile);
        SyntheticExtendedProfile.Fingerprint fingerprint = SyntheticExtendedProfile.fingerprint(profile);
        boolean staleManifest = !fingerprint.sha256().equals(manifest.fingerprintSha256());

        Path imageReport = Files.createTempFile("preflight-synthetic-image-", ".json");
        String imageJson;
        try {
            SyntheticStartupWorker.run(profile, cache, imageReport);
            imageJson = Files.readString(imageReport, StandardCharsets.UTF_8);
        } finally {
            Files.deleteIfExists(imageReport);
        }

        long indexHits = 0;
        long indexMisses = 0;
        long indexCorrupt = 0;
        long indexErrors = 0;
        long indexWriteErrors = 0;
        long jarScans = 0;
        long looseVisits = 0;
        long indexBytesHashed = 0;
        Path indexPath = SyntheticExtendedResourceIndex.path(cache, fingerprint.sha256());
        SyntheticExtendedResourceIndex.Lookup lookup = SyntheticExtendedResourceIndex.lookup(
                indexPath,
                profile,
                fingerprint.sha256());
        SyntheticExtendedResourceIndex index;
        if (lookup.status() == SyntheticExtendedResourceIndex.Status.HIT) {
            indexHits++;
            index = lookup.index();
        } else {
            switch (lookup.status()) {
                case MISS -> indexMisses++;
                case CORRUPT -> indexCorrupt++;
                case ERROR -> indexErrors++;
                default -> throw new IllegalStateException();
            }
            SyntheticExtendedResourceIndex.Build built = SyntheticExtendedResourceIndex.build(profile);
            index = built.index();
            jarScans += built.jarScans();
            looseVisits += built.looseVisits();
            indexBytesHashed += built.bytesHashed();
            try {
                index.write(indexPath, fingerprint.sha256());
            } catch (IOException | RuntimeException error) {
                indexWriteErrors++;
            }
        }

        long audioEffects = 0;
        long audioStreamed = 0;
        long audioDecoderCalls = 0;
        long audioHits = 0;
        long audioMisses = 0;
        long audioCorrupt = 0;
        long audioReadErrors = 0;
        long audioWriteErrors = 0;
        long audioBytesServed = 0;
        long audioBytesWritten = 0;
        MessageDigest audioOutputDigest = sha256();
        for (Map.Entry<String, SyntheticExtendedResourceIndex.Provider> entry
                : index.providers().entrySet()) {
            String logical = entry.getKey();
            if (!logical.toLowerCase(Locale.ROOT).endsWith(".wav")) {
                continue;
            }
            if (logical.contains("/music/")) {
                audioStreamed++;
                continue;
            }
            audioEffects++;
            SyntheticExtendedResourceIndex.Provider provider = entry.getValue();
            PreparedAudioCache.Lookup audioLookup = PreparedAudioCache.lookup(
                    cache,
                    provider.sha256(),
                    AUDIO_DECODER_POLICY_IDENTITY_SHA256,
                    PreparedAudio.Policy.FULLY_DECODED_EFFECT);
            PreparedAudio audio;
            switch (audioLookup.status()) {
                case HIT -> {
                    audioHits++;
                    audio = audioLookup.audio();
                    audioBytesServed = Math.addExact(
                            audioBytesServed,
                            audio.pcmByteCount());
                }
                case MISS -> {
                    audioMisses++;
                    audioDecoderCalls++;
                    audio = decodeAudio(index, logical, provider.sha256());
                    audioBytesWritten = Math.addExact(
                            audioBytesWritten,
                            audio.pcmByteCount());
                    if (!writeAudio(cache, audio)) {
                        audioWriteErrors++;
                    }
                }
                case CORRUPT -> {
                    audioCorrupt++;
                    audioDecoderCalls++;
                    audio = decodeAudio(index, logical, provider.sha256());
                    audioBytesWritten = Math.addExact(
                            audioBytesWritten,
                            audio.pcmByteCount());
                    if (!writeAudio(cache, audio)) {
                        audioWriteErrors++;
                    }
                }
                case ERROR, INELIGIBLE -> {
                    audioReadErrors++;
                    audioDecoderCalls++;
                    audio = decodeAudio(index, logical, provider.sha256());
                    audioBytesWritten = Math.addExact(
                            audioBytesWritten,
                            audio.pcmByteCount());
                    if (!writeAudio(cache, audio)) {
                        audioWriteErrors++;
                    }
                }
                default -> throw new IllegalStateException();
            }
            update(audioOutputDigest, logical);
            update(audioOutputDigest, audio.sourceSha256());
            update(audioOutputDigest, audio.decoderPolicyIdentitySha256());
            audioOutputDigest.update(ByteBuffer.allocate(
                            Integer.BYTES * 5 + Long.BYTES)
                    .putInt(audio.policy().id())
                    .putInt(audio.encoding().id())
                    .putInt(audio.bitsPerSample())
                    .putInt(audio.byteOrder().id())
                    .putInt(audio.sampleRateHz())
                    .putLong(audio.frameCount())
                    .array());
            audioOutputDigest.update(
                    ByteBuffer.allocate(Integer.BYTES)
                            .putInt(audio.channels())
                            .array());
            audioOutputDigest.update(audio.pcmBytes());
        }

        SyntheticGeneratedBytecodeWork.Result bytecode = SyntheticGeneratedBytecodeWork.run(
                index,
                cache,
                index.providerDigest());

        LinkedHashMap<String, Object> report = new LinkedHashMap<>();
        report.put("format", "starsector-preflight-synthetic-extended-v1");
        report.put("processId", ProcessHandle.current().pid());
        report.put("seed", manifest.seed());
        report.put("scale", manifest.scale().name().toLowerCase(Locale.ROOT));
        report.put("profileFilesValidated", fingerprint.files());
        report.put("profileBytesValidated", fingerprint.bytes());
        report.put("profileFingerprintSha256", fingerprint.sha256());
        report.put("profileManifestStale", staleManifest ? 1 : 0);
        copyLong(imageJson, report, "modCount", "imageModCount");
        copyLong(imageJson, report, "discoveredFiles", "imageDiscoveredFiles");
        copyLong(imageJson, report, "imageResources", "imageResources");
        copyLong(imageJson, report, "imageDecoderCalls", "imageDecoderCalls");
        copyLong(imageJson, report, "imageCacheHits", "imageCacheHits");
        copyLong(imageJson, report, "imageCacheMisses", "imageCacheMisses");
        copyLong(
                imageJson,
                report,
                "imageCacheCorruptFallbacks",
                "imageCacheCorruptFallbacks");
        copyLong(imageJson, report, "imageCacheReadErrors", "imageCacheReadErrors");
        copyLong(imageJson, report, "imageCacheWriteErrors", "imageCacheWriteErrors");
        copyString(
                imageJson,
                report,
                "winningProvidersSha256",
                "looseWinningProvidersSha256");
        copyString(
                imageJson,
                report,
                "preparedImageOutputsSha256",
                "preparedImageOutputsSha256");
        report.put("extendedIndexHits", indexHits);
        report.put("extendedIndexMisses", indexMisses);
        report.put("extendedIndexCorruptFallbacks", indexCorrupt);
        report.put("extendedIndexReadErrors", indexErrors);
        report.put("extendedIndexWriteErrors", indexWriteErrors);
        report.put("extendedIndexJarScans", jarScans);
        report.put("extendedIndexLooseVisits", looseVisits);
        report.put("extendedIndexBytesHashed", indexBytesHashed);
        report.put("extendedWinningResources", index.providerCount());
        report.put("extendedCollidedLogicalPaths", index.collidedPaths());
        report.put("extendedWinningProvidersSha256", index.providerDigest());
        report.put("audioEffects", audioEffects);
        report.put("audioStreamed", audioStreamed);
        report.put("audioDecoderCalls", audioDecoderCalls);
        report.put("audioCacheHits", audioHits);
        report.put("audioCacheMisses", audioMisses);
        report.put("audioCacheCorruptFallbacks", audioCorrupt);
        report.put("audioCacheReadErrors", audioReadErrors);
        report.put("audioCacheWriteErrors", audioWriteErrors);
        report.put("audioBytesServed", audioBytesServed);
        report.put("audioBytesWritten", audioBytesWritten);
        report.put(
                "preparedAudioOutputsSha256",
                HexFormat.of().formatHex(audioOutputDigest.digest()));
        report.put("javaSourceCount", bytecode.sourceCount());
        report.put("javaCompilerCalls", bytecode.compilerCalls());
        report.put("generatedBytecodeCacheHits", bytecode.cacheHits());
        report.put("generatedBytecodeCacheMisses", bytecode.cacheMisses());
        report.put(
                "generatedBytecodeCacheCorruptFallbacks",
                bytecode.cacheCorruptFallbacks());
        report.put("generatedBytecodeCacheReadErrors", bytecode.cacheErrors());
        report.put("generatedBytecodeCacheWriteErrors", bytecode.cacheWriteErrors());
        report.put("generatedClassCount", bytecode.classCount());
        report.put("generatedClassBytes", bytecode.classBytes());
        report.put("generatedClassMapSha256", bytecode.classMapSha256());
        Files.createDirectories(reportPath.toAbsolutePath().normalize().getParent());
        Files.writeString(
                reportPath,
                Json.object(report) + System.lineSeparator(),
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING,
                StandardOpenOption.WRITE);
    }

    private static PreparedAudio decodeAudio(
            SyntheticExtendedResourceIndex index,
            String logical,
            String sourceSha256) throws IOException {
        return SyntheticAudioDecoder.decodeWave(
                sourceSha256,
                AUDIO_DECODER_POLICY_IDENTITY_SHA256,
                index.readBytes(logical));
    }

    private static boolean writeAudio(Path cache, PreparedAudio audio) {
        try {
            PreparedAudioCache.write(cache, audio);
            return true;
        } catch (IOException | RuntimeException error) {
            return false;
        }
    }

    private static void copyLong(
            String json,
            Map<String, Object> output,
            String source,
            String target) throws IOException {
        Matcher matcher = Pattern.compile(
                        "\\\"" + Pattern.quote(source) + "\\\":(-?[0-9]+)")
                .matcher(json);
        if (!matcher.find()) {
            throw new IOException("Image report is missing " + source);
        }
        output.put(target, Long.parseLong(matcher.group(1)));
    }

    private static void copyString(
            String json,
            Map<String, Object> output,
            String source,
            String target) throws IOException {
        Matcher matcher = Pattern.compile(
                        "\\\"" + Pattern.quote(source) + "\\\":\\\"([^\\\"]*)\\\"")
                .matcher(json);
        if (!matcher.find()) {
            throw new IOException("Image report is missing " + source);
        }
        output.put(target, matcher.group(1));
    }

    private static MessageDigest sha256() {
        try {
            return MessageDigest.getInstance("SHA-256");
        } catch (NoSuchAlgorithmException error) {
            throw new IllegalStateException(error);
        }
    }

    private static void update(MessageDigest digest, String value) {
        byte[] bytes = value.getBytes(StandardCharsets.UTF_8);
        digest.update(ByteBuffer.allocate(Integer.BYTES)
                .putInt(bytes.length)
                .array());
        digest.update(bytes);
    }
}
