package dev.starsector.preflight.core;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

/**
 * Complete deterministic class-byte output associated with one exact compiler-context request.
 *
 * <p>The bundle deliberately stores bytecode only. Live classes, classloaders, protection domains,
 * compiler objects, and reflection state are never serialized.</p>
 */
public final class GeneratedBytecodeBundle {
    public static final int FORMAT_VERSION = 1;
    public static final int MAX_CLASS_COUNT = 10_000;
    public static final int MAX_CLASS_BYTES = 16 * 1024 * 1024;
    public static final long MAX_TOTAL_CLASS_BYTES = 512L * 1024 * 1024;
    public static final int MAX_CLASS_NAME_CHARS = 1_024;

    private final String contextKeySha256;
    private final String requestedClassName;
    private final Map<String, byte[]> classes;
    private final long totalBytecodeBytes;

    public GeneratedBytecodeBundle(
            String contextKeySha256,
            String requestedClassName,
            Map<String, byte[]> classes) {
        Hashes.decodeSha256(contextKeySha256);
        this.contextKeySha256 = contextKeySha256.toLowerCase(Locale.ROOT);
        this.requestedClassName = validateClassName(requestedClassName);
        Objects.requireNonNull(classes, "classes");
        if (classes.isEmpty()) {
            throw new IllegalArgumentException("Generated bytecode bundle requires at least one class");
        }
        if (classes.size() > MAX_CLASS_COUNT) {
            throw new IllegalArgumentException(
                    "Generated bytecode bundle exceeds " + MAX_CLASS_COUNT + " classes");
        }

        TreeMap<String, byte[]> ordered = new TreeMap<>();
        long bytes = 0;
        for (Map.Entry<String, byte[]> entry : classes.entrySet()) {
            String className = validateClassName(entry.getKey());
            byte[] bytecode = validateBytecode(className, entry.getValue());
            byte[] prior = ordered.put(className, bytecode.clone());
            if (prior != null) {
                throw new IllegalArgumentException("Duplicate generated class: " + className);
            }
            bytes = Math.addExact(bytes, bytecode.length);
            if (bytes > MAX_TOTAL_CLASS_BYTES) {
                throw new IllegalArgumentException(
                        "Generated bytecode bundle exceeds " + MAX_TOTAL_CLASS_BYTES + " total bytes");
            }
        }
        if (!ordered.containsKey(this.requestedClassName)) {
            throw new IllegalArgumentException(
                    "Generated bytecode bundle does not contain requested class " + this.requestedClassName);
        }
        this.totalBytecodeBytes = bytes;

        LinkedHashMap<String, byte[]> stable = new LinkedHashMap<>();
        ordered.forEach((name, bytecode) -> stable.put(name, bytecode));
        this.classes = Collections.unmodifiableMap(stable);
    }

    public String contextKeySha256() {
        return contextKeySha256;
    }

    public String requestedClassName() {
        return requestedClassName;
    }

    public int classCount() {
        return classes.size();
    }

    public long totalBytecodeBytes() {
        return totalBytecodeBytes;
    }

    public Map<String, byte[]> classes() {
        LinkedHashMap<String, byte[]> copy = new LinkedHashMap<>();
        classes.forEach((name, bytecode) -> copy.put(name, bytecode.clone()));
        return Collections.unmodifiableMap(copy);
    }

    public byte[] bytecode(String className) {
        byte[] bytecode = classes.get(validateClassName(className));
        return bytecode == null ? null : bytecode.clone();
    }

    Map<String, byte[]> internalClasses() {
        return classes;
    }

    public Map<String, String> bytecodeSha256() {
        LinkedHashMap<String, String> result = new LinkedHashMap<>();
        classes.forEach((name, bytecode) -> result.put(name, Hashes.sha256(bytecode)));
        return Collections.unmodifiableMap(result);
    }

    private static String validateClassName(String value) {
        Objects.requireNonNull(value, "className");
        String name = value.trim();
        if (name.isEmpty() || name.length() > MAX_CLASS_NAME_CHARS
                || name.startsWith(".") || name.endsWith(".") || name.contains("..")) {
            throw new IllegalArgumentException("Generated class name is not a canonical binary name: " + name);
        }
        for (String segment : name.split("\\.", -1)) {
            if (segment.isEmpty() || !Character.isJavaIdentifierStart(segment.charAt(0))) {
                throw new IllegalArgumentException("Generated class name is not a canonical binary name: " + name);
            }
            for (int i = 1; i < segment.length(); i++) {
                if (!Character.isJavaIdentifierPart(segment.charAt(i))) {
                    throw new IllegalArgumentException(
                            "Generated class name contains an invalid binary-name character: " + name);
                }
            }
        }
        return name;
    }

    private static byte[] validateBytecode(String className, byte[] value) {
        Objects.requireNonNull(value, "bytecode for " + className);
        if (value.length < 10 || value.length > MAX_CLASS_BYTES) {
            throw new IllegalArgumentException(
                    "Generated class " + className + " has invalid bytecode length " + value.length);
        }
        final String actualName;
        try {
            actualName = ClassFileIdentity.binaryName(value);
        } catch (IOException error) {
            throw new IllegalArgumentException(
                    "Generated class " + className + " is not a valid bounded classfile: " + error.getMessage(),
                    error);
        }
        if (!className.equals(actualName)) {
            throw new IllegalArgumentException(
                    "Generated class map key " + className + " differs from classfile identity " + actualName);
        }
        return value;
    }
}
