package dev.starsector.preflight.core;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.security.MessageDigest;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

/** Deterministic checksummed persistence for complete Janino-style generated class maps. */
public final class GeneratedBytecodeBundleIO {
    private static final byte[] MAGIC = {'S', 'P', 'J', 'B'};
    private static final int CHECKSUM_BYTES = 32;
    private static final int SHA256_BYTES = 32;
    private static final int MAX_NAME_BYTES = GeneratedBytecodeBundle.MAX_CLASS_NAME_CHARS * 4;
    private static final int MAX_FILE_BYTES = 544 * 1024 * 1024;

    private GeneratedBytecodeBundleIO() {
    }

    public static void write(Path target, GeneratedBytecodeBundle bundle) throws IOException {
        Path absolute = target.toAbsolutePath().normalize();
        Path parent = absolute.getParent();
        if (parent != null) Files.createDirectories(parent);
        byte[] bytes = toBytes(bundle);
        Path temporary = absolute.resolveSibling(
                absolute.getFileName() + ".tmp-" + ProcessHandle.current().pid() + "-" + System.nanoTime());
        boolean moved = false;
        try {
            try (FileChannel channel = FileChannel.open(
                    temporary,
                    StandardOpenOption.CREATE_NEW,
                    StandardOpenOption.WRITE)) {
                ByteBuffer buffer = ByteBuffer.wrap(bytes);
                while (buffer.hasRemaining()) channel.write(buffer);
                channel.force(true);
            }
            try {
                Files.move(
                        temporary,
                        absolute,
                        StandardCopyOption.ATOMIC_MOVE,
                        StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException ignored) {
                Files.move(temporary, absolute, StandardCopyOption.REPLACE_EXISTING);
            }
            moved = true;
        } finally {
            if (!moved) Files.deleteIfExists(temporary);
        }
    }

    public static GeneratedBytecodeBundle read(Path source) throws IOException {
        long size = Files.size(source);
        if (size < minimumFileBytes()) {
            throw new IOException("Generated bytecode bundle is too small: " + source);
        }
        if (size > MAX_FILE_BYTES) {
            throw new IOException(
                    "Generated bytecode bundle exceeds the " + MAX_FILE_BYTES + " byte safety limit: " + source);
        }
        return fromBytes(Files.readAllBytes(source));
    }

    public static byte[] toBytes(GeneratedBytecodeBundle bundle) throws IOException {
        byte[] payload = encodePayload(bundle);
        long total = minimumFileBytes() + payload.length;
        if (total > MAX_FILE_BYTES) {
            throw new IOException("Generated bytecode bundle exceeds the " + MAX_FILE_BYTES + " byte safety limit");
        }
        byte[] checksum = Hashes.sha256Bytes(payload);
        ByteArrayOutputStream bytes = new ByteArrayOutputStream((int) total);
        try (DataOutputStream output = new DataOutputStream(bytes)) {
            output.write(MAGIC);
            output.writeInt(GeneratedBytecodeBundle.FORMAT_VERSION);
            output.writeInt(payload.length);
            output.write(payload);
            output.write(checksum);
        }
        return bytes.toByteArray();
    }

    public static GeneratedBytecodeBundle fromBytes(byte[] bytes) throws IOException {
        if (bytes.length < minimumFileBytes()) {
            throw new IOException("Generated bytecode bundle is too small");
        }
        if (bytes.length > MAX_FILE_BYTES) {
            throw new IOException("Generated bytecode bundle exceeds the " + MAX_FILE_BYTES + " byte safety limit");
        }
        try (DataInputStream input = new DataInputStream(new ByteArrayInputStream(bytes))) {
            byte[] magic = input.readNBytes(MAGIC.length);
            if (!Arrays.equals(MAGIC, magic)) {
                throw new IOException("Generated bytecode bundle magic header is invalid");
            }
            int version = input.readInt();
            if (version != GeneratedBytecodeBundle.FORMAT_VERSION) {
                throw new IOException("Unsupported generated bytecode bundle version: " + version);
            }
            int payloadLength = input.readInt();
            long expectedLength = minimumFileBytes() + (long) payloadLength;
            if (payloadLength < SHA256_BYTES + Integer.BYTES * 2 || expectedLength != bytes.length) {
                throw new IOException("Generated bytecode bundle payload length is invalid");
            }
            byte[] payload = input.readNBytes(payloadLength);
            byte[] checksum = input.readNBytes(CHECKSUM_BYTES);
            if (payload.length != payloadLength || checksum.length != CHECKSUM_BYTES) {
                throw new EOFException("Generated bytecode bundle ended before its checksum");
            }
            if (!MessageDigest.isEqual(checksum, Hashes.sha256Bytes(payload))) {
                throw new IOException("Generated bytecode bundle checksum mismatch");
            }
            return decodePayload(payload);
        } catch (IllegalArgumentException | ArithmeticException error) {
            throw new IOException("Generated bytecode bundle contains invalid data: " + error.getMessage(), error);
        }
    }

    private static byte[] encodePayload(GeneratedBytecodeBundle bundle) throws IOException {
        long estimated = SHA256_BYTES + Integer.BYTES * 2L
                + stringBytes(bundle.requestedClassName())
                + bundle.totalBytecodeBytes();
        for (String className : bundle.internalClasses().keySet()) {
            estimated = Math.addExact(estimated, Integer.BYTES * 2L + CHECKSUM_BYTES + stringBytes(className));
        }
        if (estimated > MAX_FILE_BYTES) {
            throw new IOException("Generated bytecode payload exceeds the safety limit");
        }
        ByteArrayOutputStream bytes = new ByteArrayOutputStream((int) estimated);
        try (DataOutputStream output = new DataOutputStream(bytes)) {
            output.write(Hashes.decodeSha256(bundle.contextKeySha256()));
            writeString(output, bundle.requestedClassName());
            output.writeInt(bundle.classCount());
            for (Map.Entry<String, byte[]> entry : bundle.internalClasses().entrySet()) {
                writeString(output, entry.getKey());
                byte[] bytecode = entry.getValue();
                output.writeInt(bytecode.length);
                output.write(Hashes.sha256Bytes(bytecode));
                output.write(bytecode);
            }
        }
        return bytes.toByteArray();
    }

    private static GeneratedBytecodeBundle decodePayload(byte[] payload) throws IOException {
        try (DataInputStream input = new DataInputStream(new ByteArrayInputStream(payload))) {
            byte[] contextHash = input.readNBytes(SHA256_BYTES);
            if (contextHash.length != SHA256_BYTES) {
                throw new EOFException("Generated bytecode bundle ended inside its context key");
            }
            String requestedClass = readString(input);
            int classCount = input.readInt();
            if (classCount < 1 || classCount > GeneratedBytecodeBundle.MAX_CLASS_COUNT) {
                throw new IOException("Generated bytecode class count is invalid: " + classCount);
            }
            LinkedHashMap<String, byte[]> classes = new LinkedHashMap<>();
            long totalBytes = 0;
            String previous = null;
            for (int i = 0; i < classCount; i++) {
                String className = readString(input);
                if (previous != null && previous.compareTo(className) >= 0) {
                    throw new IOException("Generated bytecode classes are not in strict deterministic order");
                }
                previous = className;
                int length = input.readInt();
                if (length < 8 || length > GeneratedBytecodeBundle.MAX_CLASS_BYTES) {
                    throw new IOException("Generated class bytecode length is invalid: " + length);
                }
                byte[] expectedHash = input.readNBytes(CHECKSUM_BYTES);
                if (expectedHash.length != CHECKSUM_BYTES) {
                    throw new EOFException("Generated bytecode bundle ended inside a class hash");
                }
                byte[] bytecode = input.readNBytes(length);
                if (bytecode.length != length) {
                    throw new EOFException("Generated bytecode bundle ended inside class " + className);
                }
                if (!MessageDigest.isEqual(expectedHash, Hashes.sha256Bytes(bytecode))) {
                    throw new IOException("Generated class checksum mismatch: " + className);
                }
                totalBytes = Math.addExact(totalBytes, length);
                if (totalBytes > GeneratedBytecodeBundle.MAX_TOTAL_CLASS_BYTES) {
                    throw new IOException("Generated bytecode bundle exceeds its total-byte limit");
                }
                if (classes.put(className, bytecode) != null) {
                    throw new IOException("Generated bytecode bundle contains duplicate class " + className);
                }
            }
            if (input.available() != 0) {
                throw new IOException("Generated bytecode payload contains trailing data");
            }
            return new GeneratedBytecodeBundle(
                    java.util.HexFormat.of().formatHex(contextHash),
                    requestedClass,
                    classes);
        }
    }

    private static void writeString(DataOutputStream output, String value) throws IOException {
        byte[] bytes = value.getBytes(StandardCharsets.UTF_8);
        if (bytes.length < 1 || bytes.length > MAX_NAME_BYTES) {
            throw new IOException("Generated class name byte length is invalid");
        }
        output.writeInt(bytes.length);
        output.write(bytes);
    }

    private static String readString(DataInputStream input) throws IOException {
        int length = input.readInt();
        if (length < 1 || length > MAX_NAME_BYTES) {
            throw new IOException("Generated class name byte length is invalid: " + length);
        }
        byte[] bytes = input.readNBytes(length);
        if (bytes.length != length) {
            throw new EOFException("Generated bytecode bundle ended inside a class name");
        }
        String value = new String(bytes, StandardCharsets.UTF_8);
        if (!Arrays.equals(bytes, value.getBytes(StandardCharsets.UTF_8))) {
            throw new IOException("Generated class name is not canonical UTF-8");
        }
        return value;
    }

    private static int stringBytes(String value) {
        return value.getBytes(StandardCharsets.UTF_8).length;
    }

    private static long minimumFileBytes() {
        return MAGIC.length + Integer.BYTES * 2L + CHECKSUM_BYTES;
    }
}
