package dev.starsector.preflight.core;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Objects;

/** Fail-open content-addressed lookup for exact compiler-context bytecode bundles. */
public final class GeneratedBytecodeCache {
    private GeneratedBytecodeCache() {
    }

    public static Path bundlePath(Path cacheRoot, String contextKeySha256, String requestedClassName) {
        Objects.requireNonNull(cacheRoot, "cacheRoot");
        Hashes.decodeSha256(contextKeySha256);
        String context = contextKeySha256.toLowerCase(Locale.ROOT);
        String requestHash = Hashes.sha256(requestedClassName.getBytes(StandardCharsets.UTF_8));
        Path root = cacheRoot.toAbsolutePath().normalize();
        Path target = root.resolve("generated-bytecode")
                .resolve(context.substring(0, 2))
                .resolve(context)
                .resolve(requestHash + ".spjb")
                .normalize();
        if (!target.startsWith(root)) {
            throw new IllegalArgumentException("Generated bytecode path escaped the cache root");
        }
        return target;
    }

    public static void write(Path cacheRoot, GeneratedBytecodeBundle bundle) throws IOException {
        Path target = bundlePath(cacheRoot, bundle.contextKeySha256(), bundle.requestedClassName());
        GeneratedBytecodeBundleIO.write(target, bundle);
    }

    public static Lookup lookup(Path cacheRoot, String contextKeySha256, String requestedClassName) {
        final Path target;
        try {
            target = bundlePath(cacheRoot, contextKeySha256, requestedClassName);
        } catch (RuntimeException error) {
            return Lookup.failure(Status.ERROR, null, message(error));
        }
        if (!Files.isRegularFile(target)) {
            return Lookup.failure(Status.MISS, target, "No generated bytecode bundle exists for the exact key");
        }
        try {
            GeneratedBytecodeBundle bundle = GeneratedBytecodeBundleIO.read(target);
            String expectedContext = contextKeySha256.toLowerCase(Locale.ROOT);
            if (!bundle.contextKeySha256().equals(expectedContext)
                    || !bundle.requestedClassName().equals(requestedClassName)) {
                return Lookup.failure(Status.CORRUPT, target, "Generated bytecode bundle identity differs from its path");
            }
            return Lookup.hit(target, bundle);
        } catch (IOException | IllegalArgumentException error) {
            return Lookup.failure(Status.CORRUPT, target, message(error));
        } catch (ThreadDeath | VirtualMachineError fatal) {
            throw fatal;
        } catch (Throwable error) {
            return Lookup.failure(Status.ERROR, target, message(error));
        }
    }

    private static String message(Throwable error) {
        String value = error.getMessage();
        return value == null || value.isBlank() ? error.getClass().getSimpleName() : value;
    }

    public enum Status {
        HIT,
        MISS,
        CORRUPT,
        ERROR
    }

    public record Lookup(Status status, Path path, GeneratedBytecodeBundle bundle, String detail) {
        public Lookup {
            status = Objects.requireNonNull(status, "status");
            detail = detail == null ? "" : detail;
            if (status == Status.HIT && bundle == null) {
                throw new IllegalArgumentException("A generated bytecode cache hit requires a bundle");
            }
            if (status != Status.HIT && bundle != null) {
                throw new IllegalArgumentException("Only a generated bytecode cache hit may contain a bundle");
            }
        }

        static Lookup hit(Path path, GeneratedBytecodeBundle bundle) {
            return new Lookup(Status.HIT, path, Objects.requireNonNull(bundle, "bundle"), "");
        }

        static Lookup failure(Status status, Path path, String detail) {
            if (status == Status.HIT) throw new IllegalArgumentException("Use hit() for cache hits");
            return new Lookup(status, path, null, detail);
        }
    }
}
